// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgX2luCNpbykKLJAa7K1mMSbu_ztER1Ro',
    appId: '1:871227241863:web:812ac936cf368a71b58f22',
    messagingSenderId: '871227241863',
    projectId: 'green-terrace-c7f07',
    authDomain: 'green-terrace-c7f07.firebaseapp.com',
    storageBucket: 'green-terrace-c7f07.appspot.com',
    measurementId: 'G-RT4ME4M8FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1WvQsesJFOR0vv1VkTAkag6LHAUyVCFE',
    appId: '1:871227241863:android:6765dcce9c6c7d8ab58f22',
    messagingSenderId: '871227241863',
    projectId: 'green-terrace-c7f07',
    storageBucket: 'green-terrace-c7f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB65S1xklen8sr_-0M_jzEMa6Kicr_qHO0',
    appId: '1:871227241863:ios:0d140f46ddfaae0ab58f22',
    messagingSenderId: '871227241863',
    projectId: 'green-terrace-c7f07',
    storageBucket: 'green-terrace-c7f07.appspot.com',
    iosBundleId: 'com.biteons.greenterrace',
  );

}